server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: Aa1439422778
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB




mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info




sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    access-key-id: LTAI5t8HVopJbrjW6GnurUPx
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key-secret: WaC2ELZxYviFnBuJxpQh4pOOJwFmXc
    bucket-name: mark-web-tlias

knife4j:
  enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.sky.controller  # 替换为你的包路径






